version: "3"
services:
  auth_server:
    build:
      dockerfile: Dockerfile
      context: ./AuthServer/
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./AuthServer/build:/app/build

  blog_server:
    build:
      dockerfile: Dockerfile
      context: ./BlogServer/
    ports:
      - "5003:5003"
    volumes:
      - /app/node_modules
      - ./BlogServer/build:/app/build

  user_client:
    build:
      dockerfile: Dockerfile
      context: ./UserClient/
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./UserClient/:/app/

  admin_client:
    build:
      dockerfile: Dockerfile
      context: ./AdminClient/
    ports:
      - "5002:5002"
    volumes:
      - /app/node_modules
      - ./AdminClient/src:/app/src

  # kafka_server:
  #   image: confluentinc/cp-kafka
  #   ports:
  #     - "9092:9092"
