name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Generate SSH key
        run: |
          echo "$PRIVATE_KEY" > example.pem
          chmod 600 example.pem
          
      - name: check pem
        run:  echo "$PRIVATE_KEY"

      - name: SSH into Ubuntu instance
        run: |
          ssh -i example.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo 'Hello, Ubuntu instance!'"
          cd /home/ubuntu/dynotxt
          git pull origin production
          npm install
          npm run build_backend
          pm2 restart dynotxt_auth_server dynotxt_blog_server dynotxt_real_server
            
