name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          echo "$PRIVATE_KEY" > example.pem
          chmod 600 example.pem

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: |
            ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/dynotxt
            git pull origin production
            npm install
            npm run build
            pm2 restart 0 1 2
